# Generated by Django 4.2.6 on 2024-02-20 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklad_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationarrival',
            name='brigade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_app.brigade'),
        ),
        migrations.CreateModel(
            name='ReturnPile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_app.pile')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
