# Generated by Django 4.2.5 on 2024-02-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0002_alter_operationarrival_brigade_returnpile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pile',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
