# Generated by Django 4.2.5 on 2024-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0003_pile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigadework',
            name='type',
            field=models.CharField(choices=[('винты', 'Винты'), ('жб', 'ЖБ'), ('винты', 'Винты')], default='жб', max_length=10, verbose_name='Тип'),
        ),
    ]
