# Generated by Django 4.2.5 on 2024-02-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0004_brigadework_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdeparture',
            name='confirm_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationdeparture',
            name='manager',
            field=models.CharField(default='123', max_length=500),
        ),
        migrations.AddField(
            model_name='returnpile',
            name='confirm_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brigadework',
            name='type',
            field=models.CharField(choices=[('винты', 'Винты'), ('жб', 'ЖБ'), ('ручники', 'Ручники')], default='жб', max_length=10, verbose_name='Тип'),
        ),
    ]
