# Generated by Django 4.2.5 on 2024-02-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0005_operationdeparture_confirm_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationarrival',
            old_name='confirm',
            new_name='confirm_b',
        ),
    ]
