# Generated by Django 4.2.6 on 2024-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0007_car_alter_operationdeparture_number_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('Маз', 'Маз'), ('Камаз', 'Камаз'), ('Хино', 'Хино'), ('FAW', 'FAW'), ('Мерседес', 'Мерседес')], default='Маз', max_length=30),
        ),
    ]
