# Generated by Django 4.2.5 on 2024-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0011_operationarrival_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('company_sell', models.CharField(max_length=200)),
                ('company_buy', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_sell', models.CharField(max_length=200)),
                ('company_buy', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_sell', models.CharField(max_length=200)),
                ('company_buy', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='operationarrival',
            name='product',
        ),
        migrations.DeleteModel(
            name='OperationProduction',
        ),
    ]
