# Generated by Django 4.2.5 on 2024-03-11 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0012_armature_beton_wire_remove_operationarrival_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armature',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
