# Generated by Django 4.2.6 on 2024-03-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0013_armature_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnpile',
            name='manager',
            field=models.CharField(default='123', max_length=500),
        ),
    ]
