# Generated by Django 4.2.5 on 2024-03-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0014_returnpile_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationarrival',
            name='price',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='pile',
            name='price_armature',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pile',
            name='price_beton',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pile',
            name='price_wire',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('Неизвестно', 'Неизвестно'), ('Маз', 'Маз'), ('Камаз', 'Камаз'), ('Хино', 'Хино'), ('FAW', 'FAW'), ('Мерседес', 'Мерседес')], max_length=30),
        ),
    ]
