# Generated by Django 4.2.5 on 2024-03-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0015_operationarrival_price_pile_price_armature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pile',
            name='price_armature',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pile',
            name='price_beton',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pile',
            name='price_wire',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
