# Generated by Django 4.2.5 on 2024-03-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0016_alter_pile_price_armature_alter_pile_price_beton_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pile',
            old_name='price_wire',
            new_name='price_wire_3',
        ),
        migrations.AddField(
            model_name='pile',
            name='price_wire_4',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pile',
            name='price_wire_6',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
