# Generated by Django 4.0.6 on 2024-03-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0017_rename_price_wire_pile_price_wire_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationarrival',
            name='defect',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
