# Generated by Django 4.2.5 on 2024-03-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0018_alter_operationarrival_defect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wire4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_sell', models.CharField(max_length=200)),
                ('company_buy', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wire6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_sell', models.CharField(max_length=200)),
                ('company_buy', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='operationdeparture',
            name='confirm_bb',
            field=models.BooleanField(default=False),
        ),
    ]
