# Generated by Django 4.2.5 on 2024-03-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0020_wirehouseb'),
    ]

    operations = [
        migrations.AddField(
            model_name='wirehouseb',
            name='beton',
            field=models.IntegerField(default=0),
        ),
    ]
