# Generated by Django 4.0.6 on 2024-03-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0021_alter_car_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piles_info', models.TextField()),
                ('total_beton', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_wire_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_wire_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_wire_6', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_armature', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
