# Generated by Django 4.2.6 on 2024-03-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0021_wirehouseb_beton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
