# Generated by Django 4.0.6 on 2024-03-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0023_remove_operationarrival_pile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationdeparture',
            name='pile',
        ),
        migrations.RemoveField(
            model_name='operationdeparture',
            name='quantity',
        ),
        migrations.AddField(
            model_name='operationdeparture',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
