# Generated by Django 4.2.6 on 2024-03-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0025_lists_lopasti_tube_wirehousev_pile_to_lopast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationarrival',
            name='pile',
        ),
        migrations.RemoveField(
            model_name='operationarrival',
            name='quantity',
        ),
    ]
