# Generated by Django 4.2.6 on 2024-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0026_remove_operationarrival_pile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationarrival',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
