# Generated by Django 4.0.6 on 2024-04-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0026_alter_armature_price_alter_beton_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationarrival',
            name='price_part',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='armature',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='beton',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wire',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wire4',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wire6',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
