# Generated by Django 4.2.6 on 2024-03-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0027_operationarrival_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationdeparture',
            name='pile',
        ),
        migrations.RemoveField(
            model_name='operationdeparture',
            name='quantity',
        ),
        migrations.AddField(
            model_name='operationdeparture',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
