# Generated by Django 4.2.6 on 2024-03-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0028_remove_operationdeparture_pile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wirehousev',
            old_name='lopasti',
            new_name='lopasti108',
        ),
        migrations.AddField(
            model_name='lopasti',
            name='diameter',
            field=models.CharField(choices=[('89', '89d'), ('108', '108d'), ('133', '133d')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wirehousev',
            name='lopasti133',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wirehousev',
            name='lopasti89',
            field=models.IntegerField(default=0),
        ),
    ]
