# Generated by Django 4.2.6 on 2024-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0029_rename_lopasti_wirehousev_lopasti108_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lopasti',
            name='count',
        ),
        migrations.RemoveField(
            model_name='lopasti',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='lopasti',
            name='price',
        ),
        migrations.AddField(
            model_name='lopasti',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
