# Generated by Django 4.0.6 on 2024-04-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0030_tube_unit_price_tube108_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_sell', models.CharField(max_length=200)),
                ('company_buy', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
