# Generated by Django 4.0.6 on 2024-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0032_wirehousev_lopasti108_5_wirehousev_lopasti133_5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lopasti',
            name='details',
        ),
        migrations.AddField(
            model_name='lopasti',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lopasti',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lopasti',
            name='size',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lopasti',
            name='thickness',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
