# Generated by Django 4.0.6 on 2024-04-16 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklad_app', '0034_alter_lists_price_alter_lists5_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationArrival_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('confirm_b', models.BooleanField(default=False)),
                ('price_part', models.TextField(default=' ')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
