# Generated by Django 4.0.6 on 2024-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0036_remove_operationarrival_v_price_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('piles', models.TextField()),
                ('tubes', models.TextField()),
                ('lopastis', models.TextField()),
            ],
        ),
    ]
