# Generated by Django 4.0.6 on 2024-04-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0038_mbp_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbp_stat',
            name='admission',
            field=models.BooleanField(default=True),
        ),
    ]
