# Generated by Django 4.0.6 on 2024-04-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0040_alter_mbp_stat_brigade'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdeparture',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
