# Generated by Django 4.0.6 on 2024-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0041_operationdeparture_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armature10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_sell', models.CharField(max_length=200)),
                ('company_buy', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='pile',
            name='price_armature10',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wirehouseb',
            name='armature10',
            field=models.IntegerField(default=0),
        ),
    ]
