# Generated by Django 4.0.6 on 2024-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0042_armature10_pile_price_armature10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_armature10',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
