# Generated by Django 4.0.6 on 2024-04-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0044_del_mat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirehouseb',
            name='armature',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wirehouseb',
            name='armature10',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wirehouseb',
            name='beton',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wirehouseb',
            name='wire3',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wirehouseb',
            name='wire4',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wirehouseb',
            name='wire6',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
