# Generated by Django 4.0.6 on 2024-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0045_alter_wirehouseb_armature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdeparture',
            name='number_car',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
    ]
