# Generated by Django 4.0.6 on 2024-05-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0046_alter_operationdeparture_number_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('brigade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sklad_app.brigadework')),
            ],
        ),
    ]
