# Generated by Django 4.0.6 on 2024-05-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0048_operationdepcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdepcount',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
