# Generated by Django 4.0.6 on 2024-05-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0051_returnpiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('confirm', models.BooleanField(default=False)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_app.operationdeparture')),
            ],
        ),
    ]
