# Generated by Django 4.0.6 on 2024-06-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0054_detail_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdeparture',
            name='extra_details',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
