# Generated by Django 4.0.6 on 2024-06-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0056_senddetail_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(choices=[('Списать', 'Списать'), ('Дать', 'Дать')], max_length=30)),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_app.brigadework')),
            ],
        ),
        migrations.CreateModel(
            name='BrigadeTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_app.brigadework')),
            ],
        ),
    ]
