# Generated by Django 4.0.6 on 2024-07-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0057_tool_tool_details_brigadetool'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad_app.operationdeparture')),
            ],
        ),
    ]
